
title: Akshay Appani
logo: assets/lin.jpeg
description: I am a data professional with experience as an Educational Analyst at Toppr and a Data Engineer at Yocket. I founded my startup, Damasmart, during my undergraduate studies, driving innovative tech solutions. Having completed my master's in data science at Trine University, where I interned as a Big Data Engineer, I am now seeking roles in Big Data, Data Engineering, and Data Analysis. My journey combines technical expertise with business acumen, equipping me to implement advanced analytical strategies for efficient data management and reporting.
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Additional personal details
email: appaniaskhayvag7@gmail.com
github_username: AppaniAkshay
linkedin: https://www.linkedin.com/in/akshay-appani


